### ISSUE TITLE
Crash on setIconPolicy

### ISSUE THREAD

**Issue by arrowd** [ximion/appstream-generator#110]
When running `asgen` on FreeBSD I get the following crash on extremely rare occasions:

```
(process:83731): GLib-CRITICAL **: 14:00:59.457: g_atomic_ref_count_inc: assertion 'old_value > 0' failed

Thread 1 received signal SIGBUS, Bus error.
Object-specific hardware error.
0x000000080059ff83 in g_type_check_instance_is_fundamentally_a () from /usr/local/lib/libgobject-2.0.so.0
(gdb) bt
#0  0x000000080059ff83 in g_type_check_instance_is_fundamentally_a () at /usr/local/lib/libgobject-2.0.so.0
#1  0x0000000800584508 in g_object_unref () at /usr/local/lib/libgobject-2.0.so.0
#2  0x0000000800d0538b in asc_compose_set_icon_policy (compose=0x80485b7c0, policy=0x80481b430) at ../compose/asc-compose.c:420
#3  0x00000000004f1cd7 in _D9ascompose7ComposeQi13setIconPolicyMFCQBm10IconPolicyQmZv (this=0x280751cf00, policy=0x804e4b000) at ../build/girepo/ascompose/Compose.d:487
#4  0x000000000042194a in _D5asgen9extractor13DataExtractor6__ctorMFCQBp9datastore9DataStoreCQCn11iconhandler11IconHandlerC10localeunit10LocaleUnitCQEq12cptmodifiers21InjectedModificationsZCQGgQGdQFw
    (this=0x2807524e40, db=0x804e49240, iconHandler=0x2807435380, localeUnit=0x2807402900, modInjInfo=0x804e4b510) at ../src/asgen/extractor.d:142
#5  0x0000000000402191 in _D5asgen6engine6Engine15processPackagesMFKACQBq8backends10interfaces7PackageCQCx11iconhandler11IconHandlerCQEb12cptmodifiers21InjectedModificationsZ14__foreachbody6MFQEuZi (pkgsChunk=...) at ../src/asgen/engine.d:174
#6  0x000000000040b6ac in _D3std11parallelism__T15ParallelForeachTSQBn5range__T6ChunksTAC5asgen8backends10interfaces7PackageZQBuZQDd7opApplyMFMDFQCgZiZ4doItMFZv () at /usr/local/include/d/std/parallelism.d-mixin-4102:4148
#7  0x000000080139f33a in std.parallelism.run!(void() delegate).run(void() delegate) () at /usr/local/lib/libphobos2-ldc-debug-shared.so.102
#8  0x000000080139f315 in std.parallelism.Task!(std.parallelism.run, void() delegate).Task.impl(void*) () at /usr/local/lib/libphobos2-ldc-debug-shared.so.102
#9  0x000000080139c2ba in std.parallelism.AbstractTask.job() () at /usr/local/lib/libphobos2-ldc-debug-shared.so.102
#10 0x000000080139e639 in std.parallelism.submitAndExecute(std.parallelism.TaskPool, scope void() delegate) () at /usr/local/lib/libphobos2-ldc-debug-shared.so.102
#11 0x0000000000402101 in _D3std11parallelism__T15ParallelForeachTSQBn5range__T6ChunksTAC5asgen8backends10interfaces7PackageZQBuZQDd7opApplyMFMDFQCgZiZi (this=0x2807287400, dg=...) at /usr/local/include/d/std/parallelism.d:4154
#12 0x0000000000401f06 in _D5asgen6engine6Engine15processPackagesMFKACQBq8backends10interfaces7PackageCQCx11iconhandler11IconHandlerCQEb12cptmodifiers21InjectedModificationsZv (this=0x804e452c0, pkgs=..., iconh=0x2807435380, injMods=0x804e4b510)
    at ../src/asgen/engine.d:173
#13 0x0000000000405dda in _D5asgen6engine6Engine19processSuiteSectionMFSQBs6config5SuitexAyaCQCn15reportgenerator15ReportGeneratorZb (this=0x804e452c0, suite=..., section=..., rgen=0x804e47300) at ../src/asgen/engine.d:686
#14 0x00000000004070f2 in _D5asgen6engine6Engine3runMFAyaZv (this=0x804e452c0, suiteName=...) at ../src/asgen/engine.d:848
#15 0x0000000000384a12 in _Dmain (args=...) at ../src/app.d:182
```

**Comment by ximion** [comment]
I first thought this was an instance of the weird heisenbug, but that one appears when accessing a GResource - this issue is new! I will have a look, but most likely later (it's a low priority thing and will take a while to investigate), so if you find anything that would be of great help!
